### ISSUE TITLE
accidentally sent iDNA to ETH address

### ISSUE THREAD

**Issue by alterkahn** [idena-network/idena-docs#2]
Hello, can you tell me if there is a chance to get access to my iDNA which I accidentally sent to my ETH address?

**Comment by midenaio** [comment]
Yes, you can use your ETH private key to get access to the iDNA coins
Export your ETH wallet private key, put it into the `./datadir/keystore/nodekey` file and restart the node.

**Comment by alterkahn** [comment]
it works, thanks a lot
